#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

# Initializing the counter
count=0

# Using an until loop to display "Best School" 10 times
until [ $count -eq 10 ];
do
    echo "Best School"
    ((count++))
done
