#!/usr/bin/env bash
# This script displays "Best School" 10 times and says "Hi" on the 9th iteration

# Initializing the counter
count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ];
do
    if [ $count -eq 8 ];
then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
