#!/usr/bin/env bash
# This script displays different messages for certain loop iterations

# Initializing the counter
count=1

# Using a while loop to iterate from 1 to 10
while [ $count -le 10 ]; do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((count++))
done
