#!/usr/bin/env bash
# This script connects to the server using the private key /home/op/.ssh/school and the user ubuntu

# Use ssh with the private key and connect to the server
ssh -i /home/op/.ssh/school ubuntu@52.91.134.4
